import {test} from 'node:test';
import assert from 'node:assert/strict';
import {convertActor} from '../../scripts/importer.mjs';
import {hero} from './fixture.mjs';
const old={name:'Legacy Witch',type:'character',_id:'old-id',folder:'old-folder',img:'portraits/witch.webp',ownership:{formerPlayer:3},flags:{core:{sheetClass:'worldbuilding.SimpleActorSheet'}},system:{biography:'Backstory',health:{value:7,min:0,max:10},attributes:{Attibutes:{Mind:{value:'1d12',dtype:'Formula',label:'Mind'}}}},prototypeToken:{actorLink:false,texture:{src:'tokens/witch.webp'}},items:[{_id:'old-item',type:'weapon',name:'Wand',system:{description:'A wand',custom:42}}],effects:[{name:'Old effect'}]};
test('legacy import is a new character with formulas, resources and recoverable source',()=>{const snapshot=structuredClone(old),data=convertActor(old,'new-user');assert.deepEqual(old,snapshot);assert.equal(data._id,undefined);assert.equal(data.folder,undefined);assert.equal(data.flags,undefined);assert.deepEqual(data.ownership,{'new-user':3});assert.equal(data.system.build,null);assert.deepEqual(data.system.attributes,old.system.attributes);assert.equal(data.system.health.value,7);assert.equal(data.prototypeToken.texture.src,old.prototypeToken.texture.src);assert.equal(data.prototypeToken.actorLink,true);assert.deepEqual(data.system.legacyBackup.source,old);assert.equal(data.items[0].type,'item');assert.equal(data.items[0].system.legacyBackup.system.custom,42);assert.equal(data.items[0]._id,undefined);});
test('module build restores allocations, recalculates dice and preserves Play Mode',()=>{const source=structuredClone(old);source.flags['saga-character-studio']={build:{schemaVersion:1,character:{...hero,attributeDice:{mind:'1d100'}}},session:{heroism:2,conditions:['Injured'],rolls:[]}};const data=convertActor(source,'new-user');assert.equal(data.system.build.character.attributeDice.mind,'1d10');assert.equal(data.system.attributes.Attibutes.Mind.value,'1d10');assert.equal(data.system.attributes.Powers.saga0.value,'1d10 + 5');assert.deepEqual(data.system.session,source.flags['saga-character-studio'].session);});
test('native SAGA exports can also be imported as copies',()=>{const data=convertActor({...old,system:{...old.system,build:{schemaVersion:1,character:hero}}},'new-user');assert.deepEqual(convertActor(data,'other').system.build,data.system.build);});
test('reject unsupported or invalid build before creation',()=>{assert.throws(()=>convertActor({type:'npc'},'u'),/exported/);assert.throws(()=>convertActor({...old,system:{build:{schemaVersion:2}}},'u'),/newer/);assert.throws(()=>convertActor({...old,system:{build:{schemaVersion:1,character:{...hero,level:2}}}},'u'),/spend exactly/);});
